integration:
  azure:
    search:
      url: "https://api.bing.microsoft.com/v7.0/"
      news:
        subscription-key: "subscription-key"
news-sources:
  ru: iz.ru, tsargrad.tv, rbc.ru, aif.ru, rg.ru
  eu: bbc.com, svoboda.org
